apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-volume
  labels:
    app: db
spec:
  storageClassName: microk8s-hostpath
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi